### ISSUE TITLE
create-react-component script failing

### ISSUE THREAD

**Issue by idkjs** [OffGridNetworks/fuse-box-create-react-app#1]
```
npm install -g fuse-box-create-react-app

create-react-component my-component
cd my-component/
npm start
```
output:
```sh
$ create-react-component my-component
-bash: create-react-component: command not found
```
 This worked though, `fuse-box-create-react-app fuse-app-re --scripts-version reason-scripts`!

**Comment by guybarnard** [comment]
Thanks for heads up.  Am going through a fair bit of publishing currently to get both JS and typescripts versions working.   Wasnt sure anyone else was using it but if you can hold off 24 hours it should be cleaned up by then./

**Comment by guybarnard** [comment]
Version 3.0.73 and later should now support create-react-component using StoryBook.   Future templates are planned with catalog or styleguidist.   Due to possible breaking changes from 2.0x, please uninstall any global versions of fuse-box-create-react-app first and then reinstall.
