### ISSUE TITLE
Can't display jpg or png, only svg

### ISSUE THREAD

**Issue by Janaka-Steph** [OffGridNetworks/fuse-box-create-react-app#5]
Hello,

I can't display jpg or png images, only svg. I am wondering if the Image Base64 Plugin could be the issue?
Can I add it by myself? How to customize the conf?

Thank you

**Comment by guybarnard** [comment]
yes, just run `npm run ejectconfig` and just the config file is ejected which you can then edit to add your own plugins for the given workspace only.   Unlike eject, this is actually reversible, to uneject, just delete the config folder;  if present, it uses it.

**Comment by Janaka-Steph** [comment]
Thank you @guycreate, it works, the ImageBase64 Plugin was necessary. 
But would it be better to have it by default?  I think it's a basic Plugin to have by default.

Best!
